import 'package:flutter/material.dart';
const Color whiteColor = Colors.white;
const Color blackColor = Colors.black;
const Color greyColor = Colors.grey;
const Color appGreyColor = Color(0xFFDDD9E6);
const Color appMainColor = Colors.deepOrange;
const Color mainLightColor = Color(0xFFFFFFFF);
const Color secondLightColor = Color(0xFFEAEDED);
const Color mainDarkColor = Color(0xFF25292A);
const Color secondDarkColor = Color(0xFF373A3A);